[package]
name = "blake3-proof-of-work"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.blake3]
version = "1.3.0"

[dependencies.rand]
version = "0.8.4"

[dependencies.num_cpus]
version = "1.13.1"
